version: '3'
services:
    pentaho:
        container_name: pentaho
        image: myserver/pentahovolume
        restart: always      
        privileged: true
        ports:
            - "8080:8080"
        volumes:
            - /mnt/pentaho-data/hsqldb:/home/pentaho/pentaho-server/data/hsqldb 
            - /mnt/pentaho-data/repo:/home/pentaho/pentaho-server/pentaho-solutions/system/jackrabbit/repository 






